---
- hosts: all
  become: true
  tasks:

  - name: install Apache HTTP server and PHP
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

  - name: Check if Apache HTTP server is enabled
    command: systemctl is-enabled httpd
    register: apache_enabled
    changed_when: false
    ignore_errors: true


  - name: Ensure Apache HTTP server is enabled and started if not enabled
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: apache_enabled.rc != 0


