---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "centos"

  - name: install Apache HTTP server package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "centos"

  - name: install PHP support for apache
    yum:
      name: php
      state: latest
    when: ansible_distribution == "centos"

  - name: Check if Apache HTTP server is enabled
    shell: systemctl is-enabled httpd
    register: apache_enabled
    changed_when: false
    ignore_errors: true

  - name: Ensure Apache HTTP server is enabled and started if not enabled
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: apache_enabled.stdout != "enabled"

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: add php suppport for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"

  - name: Check if Apache HTTP server is enabled
    shell: systemctl is-enabled httpd
    register: apache_enabled
    changed_when: false
    ignore_errors: true

  - name: Ensure Apache HTTP server is enabled and started if not enabled
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: apache_enabled.stdout != "enabled"
