---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes 

  - name: install Apache HTTP server package
    yum:
      name: httpd
      state: latest

  - name: install PHP support for apache
    yum:
      name: php
      state: latest

  - name: Check if Apache HTTP server is enabled
    shell: systemctl is-enabled httpd
    register: apache_enabled
    changed_when: false
    ignore_errors: true

  - name: Ensure Apache HTTP server is enabled and started if not enabled
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: apache_enabled.stdout != "enabled"













#---

#- hosts: all
 # become: true
 # tasks:

# - name: update repository index
 #   yum:
  #    update_cache: yes 

 #- name: install apache HTTP server package
  #  yum:
   #   name: httpd
    #  state: present
