- name: install Apache HTTP server and PHP for CentOS
  tags: apache,httpd,php
  package:
     name:
        - "{{ apache_package_name }}"
        - "{{ php_package_name }}"
     state: latest


- name: Check if Apache HTTP server is enabled
  command: systemctl is-enabled httpd
  register: apache_enabled
  changed_when: false
  ignore_errors: true

- name: Ensure Apache HTTP server is enabled and started if not enabled
  systemd:
      name: "{{ apache_service }}"
      state: started
      enabled: yes
  when: apache_enabled.rc != 0

- name: copy default html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    omode: 0644 

