 - name: install unzip
   package:
        name: unzip

 - name: install terraform
   unarchive:
        src: https://releases.hashicorp.com/ter>
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

